### ISSUE TITLE
Incorrect information printed after successful xcp discovery

### ISSUE THREAD

**Issue by mjidhage** [CaringCaribou/caringcaribou#1]
Ran ./cc.py xcp discovery -min 0x3 towards a target. The discovery got a response on one of the CONNECT attempts, decoded the response and continued searching for more. When the search reached 0x7ff the printout "XCP could not be found: Brute force of range 0x3-0x7ff completed", which indicates failure.

**Comment by kasperkarlsson** [comment]
Solved.
