### ISSUE TITLE
xcp discovery报错咯

### ISSUE THREAD

**Issue by L-ss666** [CaringCaribou/caringcaribou#101]
![image](https://github.com/CaringCaribou/caringcaribou/assets/75765221/b7d4bc32-1955-44e3-98f6-09b541a1eae1)

**Comment by kasperkarlsson** [comment]
Hello,

I believe this is due to a lack of a `.canrc` file specifying interface defaults.

Instructions on how to fix this can be found at https://github.com/CaringCaribou/caringcaribou/blob/master/documentation/troubleshooting.md#missing-default-configuration-file-for-python-can

**Comment by kasperkarlsson** [comment]
Closing the issue, assuming that the suggested solution worked. Feel free to open a new issue (with more details on setup and usage) otherwise!
