### ISSUE TITLE
in doip module，discovery services that ecu supports

### ISSUE THREAD

**Issue by zb123cdfg** [CaringCaribou/caringcaribou#111]
![image](https://github.com/CaringCaribou/caringcaribou/assets/141092512/2b77fe08-9c78-4a99-908a-0b3212d5b908)
how to understand these code in picture,specially response_id = service_id

**Comment by kasperkarlsson** [comment]
I am not sure which issue you are facing here, would you care to elaborate?

**Comment by kasperkarlsson** [comment]
Closing this issue, as no further clarification has been received.
