### ISSUE TITLE
Failed to receive CANFD packets!

### ISSUE THREAD

**Issue by sut4nd0** [CaringCaribou/caringcaribou#112]
Failed to receive CANFD packets!

**Comment by kasperkarlsson** [comment]
Without any further details, this will be hard to look into.

**Comment by sut4nd0** [comment]
By reading the code, I found the problem. When connecting CANFD, I need to specify like: `bus = can.interface.Bus(channel='can0', interface='socketcan', fd=True, bitrate=500000, dbitrate=2000000)`.
I think the most important of these is `fd=True, bitrate=500000, dbitrate=2000000`.

**Comment by sut4nd0** [comment]
> Without any further details, this will be hard to look into.

By reading the code, I found the problem. When connecting CANFD, I need to specify like: `bus = can.interface.Bus(channel='can0', interface='socketcan', fd=True, bitrate=500000, dbitrate=2000000)`.
I think the most important of these is `fd=True, bitrate=500000, dbitrate=2000000`.

**Comment by kasperkarlsson** [comment]
I am happy to hear that you managed to resolve your issue. Thanks for letting me know!
