### ISSUE TITLE
UDS module naming question

### ISSUE THREAD

**Issue by n135c10r** [CaringCaribou/caringcaribou#121]
Currently, CaringCaribou has two modules based on UDS: `uds` and `doip`. The existing naming convention doesn't fully reflect the current setup. Since CAN is no longer the only bus where we handle UDS, it makes sense to align with the terminology introduced after implementing DoIP. 
What’s your opinion on renaming the UDS module dedicated to CAN from `uds` to `docan`, along with all necessary changes in documentation and other related areas?

**Comment by kasperkarlsson** [comment]
Hello!

Thank you for your input. There does not seem to be any confusion worth mentioning regarding this so far, and changing the wording would risk breaking users' scripts without adding much value. I do hence not believe such a change is currently necessary.

**Comment by n135c10r** [comment]
Hello. 
Sure, your arguments are absolutely reasonable. It was just a casual suggestion from a beginner user 😉
