### ISSUE TITLE
Add tester-present feature in dcm

### ISSUE THREAD

**Issue by mjidhage** [CaringCaribou/caringcaribou#17]
To enable manual testing through 'send'

**Comment by mjidhage** [comment]
Implement loop-feature in send instead. (delay and msg is already available)

**Comment by kasperkarlsson** [comment]
Enhancement request to add a loop feature moved to separate issue: https://github.com/CaringCaribou/caringcaribou/issues/18

Due to this, a separate "Tester Present" functionality will not be necessary.
