### ISSUE TITLE
Add possibility to continue after successful diagnostic discovery

### ISSUE THREAD

**Issue by mjidhage** [CaringCaribou/caringcaribou#2]
executing "./cc.py dcm discovery" searches for diagnostic services by sending TesterPresent to one ArbID at a time. After a successful hit, the module hit reports what arbid replied and what arbid was used in the reply.

The user can continue to search the rest of the adress space using -min flag but to make it even easier for the user a question to the user would be useful "Do you want to continue the search?". Another approach could be to automatically continue the search. If the user only is interested the first result he/she can interrupt the search with ctrl-c

**Comment by kasperkarlsson** [comment]
Implemented in https://github.com/CaringCaribou/caringcaribou/commit/14670bed7b594711ea86f6e366da3b112a671283 using _-nostop_ flag
