### ISSUE TITLE
Remove subfunction indicies #1 brute force

### ISSUE THREAD

**Issue by mjidhage** [CaringCaribou/caringcaribou#24]
Using dcm subfunction source dest service 1 (with index = 1) actually bruteforces the service-field. Makes no sense since it is part of another argument. Either change the meaning of the index or make 0 and 1 illegal input

**Comment by kasperkarlsson** [comment]
Fixed in https://github.com/CaringCaribou/caringcaribou/commit/d7df874e903df95bc1f6f7e02e5c2ed3247e3e53
