### ISSUE TITLE
0x7ff erroneously detected as diagnostic service

### ISSUE THREAD

**Issue by mjidhage** [CaringCaribou/caringcaribou#25]
While running dcm discovery a 0x733/0x633 combo appeared in the result screen. A new discovery started at 0x734 with nostop option detected a 0x7ff/0x633 combo. A bit suspicious since it is the last id before automatic stop of scan (assumption does not support extended id). Needs verification.

**Comment by kasperkarlsson** [comment]
Tried to do this multiple times, both with and without min_id setting specified during discovery with `-nostop` set. Could not observe this behavior in any of the runs.

Closing since the error could not be reproduced and further technical details are unavailable.
