### ISSUE TITLE
TypeError: bruteforce_data_new() got an unexpected keyword argument 'callback_end' 

### ISSUE THREAD

**Issue by bensya** [CaringCaribou/caringcaribou#6]
Run dcm subfuc instruction as follows, and got an error:

python cc.py dcm subfunc 0x710 0x77a 0x24 2

---
## CARING CARIBOU v0.1

Loaded module 'dcm'

Starting DCM sub-function discovery

No sub-functions were found

Traceback (most recent call last):
  File "cc.py", line 114, in <module>
    main()
  File "cc.py", line 106, in main
    mod.module_main(args.module_args)
  File "modules/dcm.py", line 367, in module_main
    args.func(args)
  File "modules/dcm.py", line 299, in subfunc_discovery
    callback_end=finished)
TypeError: bruteforce_data_new() got an unexpected keyword argument 'callback_end'

**Comment by kasperkarlsson** [comment]
Solved in https://github.com/CaringCaribou/caringcaribou/commit/334b25ce2dddea696f6679444d717846b3174d22
