### ISSUE TITLE
dcm subfunc always generates length 3

### ISSUE THREAD

**Issue by fearfulspoon** [CaringCaribou/caringcaribou#65]
No matter what indices are provided, the function always generates length 3.

See pull request for suggested fix:
https://github.com/CaringCaribou/caringcaribou/pull/64

**Comment by kasperkarlsson** [comment]
PR merged. Thank you very much for your contribution, @fearfulspoon!

Would you like to be listed under the Contributors section at https://github.com/CaringCaribou/caringcaribou#contributors ? If so, just let me know which name/handle to add :slightly_smiling_face:

**Comment by fearfulspoon** [comment]
I would like that, thank you. FearfulSpoon works.
