### ISSUE TITLE
Attempted relative import in non-package

### ISSUE THREAD

**Issue by HeartSleep** [CaringCaribou/caringcaribou#81]
python2：

Traceback (most recent call last):
  File "caringcaribou.py", line 7, in <module>
    from .utils import can_actions
ValueError: Attempted relative import in non-package

**Comment by HeartSleep** [comment]
Traceback (most recent call last):
  File "caringcaribou.py", line 7, in <module>
    from .utils import can_actions
ImportError: attempted relative import with no known parent package

**Comment by HeartSleep** [comment]
I followed the new installation instructions to install the tool, but I am unable to call it in the shell.What other methods are there?

**Comment by HeartSleep** [comment]
Hello @kasperkarlsson.
Thanks! I installed it according to the new installation method, running it directly in the shell found that it would run successfully.

**Comment by kasperkarlsson** [comment]
That is great to hear. I will close this issue then, thanks for using Caring Caribou 😺
