### ISSUE TITLE
./cc.py dump Not Working giving error [Virtual Port is Open]

### ISSUE THREAD

**Issue by shaaa9** [CaringCaribou/caringcaribou#92]
There is no cc.py file in package
after following command  
 ./caringcaribou.py 
Getting Following error'
"
Traceback (most recent call last):
  File "/home/kali/caringcaribou/caringcaribou/./caringcaribou.py", line 7, in <module>
    from .utils import can_actions
ImportError: attempted relative import with no known parent package"
                                                                      
ReInstalled Several times

**Comment by kasperkarlsson** [comment]
Please follow the installation and usage instructions.

https://github.com/CaringCaribou/caringcaribou#get-started
