### ISSUE TITLE
can.exceptions.CanInterfaceNotImplementedError:Unknow interface type "None"

### ISSUE THREAD

**Issue by wangzihaoha** [CaringCaribou/caringcaribou#95]
I want to use caringcaribou to fuzz the vehicle can bus. I connected the pcan and then used two commands "sudo modprobe can", "sudo ip link set can0 up type can bitrate 500000", then I used "ip link show can0", can see the information of can0, but I use the command "cc.py fuzzer random", an error of unknown interface type "None" appeared. I used cc.py -i can0 fuzzer random and still got the same error. I couldn't get any message by using the command "candump can0" , but my colleague can capture the messages of the can bus normally by using pcan view.How to solve this problem, thank you very much

**Comment by kasperkarlsson** [comment]
Hello @wangzihaoha,

It sounds like the following point of the troubleshooting guide will help you:

`Missing default configuration file for python-can`
https://github.com/CaringCaribou/caringcaribou/blob/master/documentation/troubleshooting.md#missing-default-configuration-file-for-python-can

**Comment by wangzihaoha** [comment]
Hello @kasperkarlsson ,
With your help, I solved the problem and successfully tested it. I noticed that the length of the fuzzer module can be set. I would like to ask whether it is possible to do the fuzz test of the canfd protocol by modifying the length.Thank you
